<script>
	import { Button, Input, Label, FormGroup } from '$lib';
	import { UploadDropzone, createUploader } from '$lib/uploadthing';

	let {
		isOpen = false,
		event = null,
		onSave,
		onCancel
	} = $props();

	const uploader = createUploader("imageUploader", {
		onClientUploadComplete: (res) => {
			console.log("Files: ", res);
			if (res && res.length > 0) {
				// We return { uploadedBy, url } from core.js
				const fileUrl = res[0].serverData?.url || res[0].url;
				formData.image = fileUrl;
				imagePreview = fileUrl;
			}
		},
		onUploadError: (error) => {
			console.error(error);
			uploadError = error.message;
		}
	});
	
	// Form state
	let formData = $state({
		title: '',
		description: '',
        date: new Date().toISOString().split('T')[0],
		location: '',
		address: '',
		mapsLink: '',
		image: '',
		link: ''
	});
	
	// UI state
	let imagePreview = $state(null);
	let isUploading = $state(false);
	let uploadError = $state(null);
	let isAutoGeneratedMapsLink = $state(true); // Track if maps link is auto-generated
	
	// Load event data when editing
	$effect(() => {
		if (event) {
			formData = {
				title: event.title || '',
				description: event.description || '',
				date: event.date ? new Date(event.date).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
				location: event.location || '',
				address: event.address || '',
				mapsLink: event.mapsLink || '',
				image: event.image || '',
				link: event.link || ''
			};
			// Set preview for existing image
			if (event.image) {
				imagePreview = event.image;
			} else {
				imagePreview = null;
			}
        } else {
			formData = {
				title: '',
				description: '',
				date: new Date().toISOString().split('T')[0],
				location: '',
				address: '',
				mapsLink: '',
				image: '',
				link: ''
			};
			imagePreview = null;
		}
		uploadError = null;
		
		// Check if the loaded event has a custom maps link
		if (event?.mapsLink && event.mapsLink.trim()) {
			isAutoGeneratedMapsLink = false;
		} else {
			isAutoGeneratedMapsLink = true;
		}
	});
	
	// Auto-generate Google Maps link from address
	$effect(() => {
		const address = formData.address;
		
		// Only auto-generate if address exists and link is auto-generated (not manually edited)
		if (address && address.trim() && isAutoGeneratedMapsLink) {
			// Generate Google Maps search URL
			const encodedAddress = encodeURIComponent(address.trim());
			const generatedLink = `https://www.google.com/maps/search/?api=1&query=${encodedAddress}`;
			formData.mapsLink = generatedLink;
		} else if (!address || !address.trim()) {
			// Clear the link if address is cleared
			if (isAutoGeneratedMapsLink) {
				formData.mapsLink = '';
			}
		}
	});
	
	// Clear image
	function clearImage() {
		formData.image = '';
		imagePreview = null;
	}
	
	async function handleSubmit(e) {
		e.preventDefault();
		
		const eventData = {
			id: event?.id || crypto.randomUUID(),
			title: formData.title,
			description: formData.description,
			date: formData.date,
			location: formData.location,
			address: formData.address,
			mapsLink: formData.mapsLink,
			image: formData.image,
			link: formData.link
		};
		
		onSave(eventData);
	}
	
	function handleCancel() {
		onCancel();
	}
</script>

{#if isOpen}
	<div class="modal-overlay" onclick={handleCancel} onkeydown={(e) => e.key === 'Escape' && handleCancel()} role="button" tabindex="-1">
		<div class="modal-container" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()} role="dialog" aria-modal="true" tabindex="-1">
			<div class="modal-header">
				<h2 class="modal-title">
					{event ? 'Edit Event' : 'Add New Event'}
				</h2>
				<button class="close-btn" onclick={handleCancel} aria-label="Close modal">
					<i class="fas fa-times"></i>
				</button>
			</div>
			
			<form onsubmit={handleSubmit} class="modal-form">
				<FormGroup>
					<Label htmlFor="title" required>Event Title</Label>
					<Input
						type="text"
						name="title"
						bind:value={formData.title}
						placeholder="e.g., Renaissance Fair 2025"
						required
					/>
				</FormGroup>
				
				<FormGroup>
					<Label htmlFor="description" required>Description</Label>
					<textarea
						name="description"
						bind:value={formData.description}
						placeholder="Describe your event..."
						required
					class="textarea"
					rows="5"
				></textarea>
			</FormGroup>
			
			<div class="form-row">
				<FormGroup>
					<Label htmlFor="date" required>Event Date</Label>
					<Input
						type="date"
						name="date"
						bind:value={formData.date}
						required
					/>
				</FormGroup>
				
				<FormGroup>
					<Label htmlFor="location">Location Name</Label>
					<Input
						type="text"
						name="location"
						bind:value={formData.location}
						placeholder="e.g., Downtown Plaza"
					/>
				</FormGroup>
			</div>
			
			<!-- Address and Maps Link -->
			<FormGroup>
				<Label htmlFor="address">Street Address</Label>
				<Input
					type="text"
					name="address"
					bind:value={formData.address}
					placeholder="e.g., 123 Main St, City, State 12345"
				/>
			</FormGroup>
			
			<FormGroup>
				<Label htmlFor="mapsLink">Google Maps Link</Label>
				<Input
					type="text"
					name="mapsLink"
					bind:value={formData.mapsLink}
					placeholder="Auto-generated from address or paste custom link..."
					oninput={() => { isAutoGeneratedMapsLink = false; }}
				/>
				<p class="field-hint">
					<i class="fas fa-magic"></i>
					Auto-filled when you enter an address above
				</p>
			</FormGroup>
			
			<FormGroup>
				<Label htmlFor="image">Event Image</Label>
				<div class="image-upload-section">
					{#if imagePreview}
						<div class="image-preview">
							<img src={imagePreview} alt="Event preview" />
							<button 
								type="button" 
								class="clear-image-btn"
								onclick={clearImage}
								disabled={isUploading}
							>
								<i class="fas fa-trash"></i>
								Remove Image
							</button>
						</div>
					{:else}
						<div class="upload-area">
							<UploadDropzone uploader={uploader} />
						</div>
					{/if}
					
					{#if uploadError}
						<p class="error-message">{uploadError}</p>
					{/if}
					
					{#if isUploading}
						<p class="uploading-message">Uploading image...</p>
					{/if}
				</div>
			</FormGroup>
				
				<FormGroup>
					<Label htmlFor="link">Event Link</Label>
					<Input
						type="text"
						name="link"
						bind:value={formData.link}
						placeholder="https://example.com/event-details"
					/>
				</FormGroup>
				
				<div class="modal-actions">
					<Button type="button" variant="ghost" onclick={handleCancel}>
						Cancel
					</Button>
					<Button type="submit" variant="primary">
						<i class="fas fa-save"></i>
						<span>{event ? 'Update' : 'Create'} Event</span>
					</Button>
				</div>
			</form>
		</div>
	</div>
{/if}

<style lang="scss">
	.modal-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.7);
		backdrop-filter: blur(4px);
		z-index: 2000;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 1rem;
		animation: fadeIn 0.2s ease;
	}
	
	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}
	
	.modal-container {
		background: var(--nav-bg);
		border: 1px solid var(--panel-border);
		border-radius: 16px;
		width: fit-content;
		max-width: 90vw;
		max-height: 90vh;
		overflow-y: auto;
		box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);
		animation: slideUp 0.3s ease;
		
		/* Custom scrollbar */
		&::-webkit-scrollbar {
			width: 8px;
		}
		
		&::-webkit-scrollbar-track {
			background: transparent;
		}
		
		&::-webkit-scrollbar-thumb {
			background: var(--border-primary);
			border-radius: 4px;
		}
		
		&::-webkit-scrollbar-thumb:hover {
			background: var(--accent);
		}
	}
	
	@keyframes slideUp {
		from {
			opacity: 0;
			transform: translateY(20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
	
	.modal-header {
		display: flex;
		// justify-content: space-between;
		align-items:first baseline;
		padding: 1.5rem 2rem;
		border-bottom: 1px solid var(--panel-border);
	}
	
	.modal-title {
		color: var(--text-primary);
		font-size: 1.5rem;
		font-weight: 700;
		margin: 0;
	}
	
	.close-btn {
		width: 36px;
		height: 36px;
		display: flex;
		align-items: center;
		justify-content: center;
		background: transparent;
		border: 1px solid var(--border-secondary);
		border-radius: 8px;
		color: var(--muted);
		cursor: pointer;
		transition: all 0.2s ease;
		position: absolute;
		top: 1.5rem;
		right: 2rem;
		
		&:hover {
			border-color: var(--accent);
			color: var(--accent);
			background: rgba(167, 139, 250, 0.1);
		}
	}
	
	.modal-form {
		padding: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		align-items: center;
		text-align: start;
	}
	
	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
		width: 100%;
		
		@media (max-width: 600px) {
			grid-template-columns: 1fr;
		}
	}
	
	.textarea {
		width: -webkit-fill-available;
		padding: 0.75rem 1rem;
		background: var(--bg-secondary);
		border: 1px solid var(--border-secondary);
		border-radius: 12px;
		color: var(--text-secondary);
		font-size: 1rem;
		outline: none;
		transition: all 0.3s ease;
		font-family: inherit;
		resize: vertical;
		min-height: 120px;
		line-height: 1.5;
		
		&:focus {
			border-color: var(--accent);
			box-shadow: 0 0 0 3px rgba(167, 139, 250, 0.1);
			background: var(--bg-primary);
		}
		
		&::placeholder {
			color: var(--muted-2);
		}
		
		&:hover:not(:focus) {
			border-color: var(--border-primary);
		}
	}
	
	.image-upload-section {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	
	.image-preview {
		position: relative;
		border-radius: 8px;
		overflow: hidden;
		
		img {
			width: 100%;
			height: 300px;
			object-fit: cover;
			display: block;
		}
		
		.clear-image-btn {
			position: absolute;
			top: 0.5rem;
			right: 0.5rem;
			display: flex;
			align-items: center;
			gap: 0.5rem;
			padding: 0.5rem 1rem;
			background: rgba(0, 0, 0, 0.7);
			color: white;
			border: none;
			border-radius: 6px;
			cursor: pointer;
			font-size: 0.9rem;
			transition: all 0.2s ease;
			
			&:hover:not(:disabled) {
				background: rgba(0, 0, 0, 0.9);
				transform: scale(1.05);
			}
			
			&:disabled {
				opacity: 0.5;
				cursor: not-allowed;
			}
		}
	}
	
	.upload-area {
		position: relative;
		display: flex;
		align-items: center;
		justify-content: center;
		
		&.dragging {
			.upload-label {
				border-color: var(--accent);
				background: rgba(167, 139, 250, 0.15);
				transform: scale(1.02);
				
				i {
					color: var(--accent);
					animation: bounce 0.6s ease infinite;
				}
			}
		}
		
		.file-input {
			display: none;
		}
		
		.upload-label {
			width: 100%;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			padding: 2rem;
			border: 2px dashed var(--border-primary);
			border-radius: 8px;
			cursor: pointer;
			transition: all 0.2s ease;
			background: var(--bg-secondary);
			pointer-events: none;
			
			i {
				font-size: 2rem;
				color: var(--accent);
				margin-bottom: 0.5rem;
				transition: all 0.2s ease;
			}
			
			&:hover {
				border-color: var(--accent);
				background: rgba(167, 139, 250, 0.05);
			}
		}
	}
	
	@keyframes bounce {
		0%, 100% {
			transform: translateY(0);
		}
		50% {
			transform: translateY(-10px);
		}
	}
	
	.upload-text {
		color: var(--text-primary);
		font-weight: 600;
		margin: 0;
		font-size: 1rem;
	}
	
	.upload-hint {
		color: var(--muted);
		font-size: 0.85rem;
		margin: 0.25rem 0 0;
	}
	
	.error-message {
		color: #ff6b6b;
		font-size: 0.9rem;
		margin: 0;
	}
	
	.uploading-message {
		color: var(--accent);
		font-size: 0.9rem;
		margin: 0;
		text-align: center;
	}
	
	.field-hint {
		color: var(--muted);
		font-size: 0.85rem;
		margin: 0.5rem 0 0;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		
		i {
			color: var(--accent);
			font-size: 0.8rem;
		}
	}
	
	.modal-actions {
		display: flex;
		justify-content: flex-start;
		gap: 1rem;
		margin-top: 1rem;
		padding-top: 1.5rem;
		border-top: 1px solid var(--panel-border);
		width: 100%;
	}
	
	@media (max-width: 600px) {
		.modal-container {
			max-height: 95vh;
		}
		
		.modal-header,
		.modal-form {
			padding: 1.5rem;
		}
		
		.modal-title {
			font-size: 1.25rem;
		}
	}
</style>
