<script>
	import { Button, Input, Label, FormGroup } from '$lib';

	let {
		isOpen = false,
		testimonial = null,
		onSave,
		onCancel
	} = $props();

	// Form state
	let formData = $state({
		name: '',
		text: '',
		stars: '',
		image: '',
		link: ''
	});
	
	// UI state
	let imagePreview = $state(null);
	let isUploading = $state(false);
	let uploadError = $state(null);
	let fileInput = $state(undefined);
	let isDragging = $state(false);
	let isAutoGeneratedMapsLink = $state(true); // Track if maps link is auto-generated
	
// Load testimonial data when editing
$effect(() => {
	if (testimonial) {
		formData = {
			name: testimonial.name || '',
			text: testimonial.text || '',
			stars: testimonial.stars || '',
			image: testimonial.image || '',
			link: testimonial.link || ''
		};
		imagePreview = testimonial.image || null;
	} else {
		formData = {
			name: '',
			text: '',
			stars: '',
			image: '',
			link: ''
		};
		imagePreview = null;
	}
	uploadError = null;
});
	
	// Handle file selection and upload
	async function handleFileChange(e) {
		const target = e.target;
		const file = target.files?.[0];
		
		if (!file) return;
		
		await uploadFile(file);
	}
	
	// Shared file upload logic
	async function uploadFile(file) {
		// Validate file type
		if (!file.type.startsWith('image/')) {
			uploadError = 'Please select an image file';
			return;
		}
		
		// Validate file size (max 5MB)
		if (file.size > 5 * 1024 * 1024) {
			uploadError = 'Image must be smaller than 5MB';
			return;
		}
		
		// Create form data for upload
		const formDataUpload = new FormData();
		formDataUpload.append('file', file);
		
		isUploading = true;
		uploadError = null;
		
		try {
			const response = await fetch('/api/upload-event-image', {
				method: 'POST',
				body: formDataUpload
			});
			
			if (!response.ok) {
				throw new Error('Upload failed');
			}
			
			const data = await response.json();
			formData.image = data.imagePath;
			
			// Create preview
			const reader = new FileReader();
			reader.onload = (event) => {
				imagePreview = event.target?.result;
			};
			reader.readAsDataURL(file);
		} catch (error) {
			uploadError = error instanceof Error ? error.message : 'Upload failed';
		} finally {
			isUploading = false;
		}
	}
	
	// Drag and drop handlers
	function handleDragOver(e) {
		e.preventDefault();
		e.stopPropagation();
	}
	
	function handleDragEnter(e) {
		e.preventDefault();
		e.stopPropagation();
		isDragging = true;
	}
	
	function handleDragLeave(e) {
		e.preventDefault();
		e.stopPropagation();
		// Only set to false if we're leaving the upload area itself, not a child element
		const target = e.currentTarget;
		const relatedTarget = e.relatedTarget;
		if (!target.contains(relatedTarget)) {
			isDragging = false;
		}
	}
	
	async function handleDrop(e) {
		e.preventDefault();
		e.stopPropagation();
		isDragging = false;
		
		const files = e.dataTransfer?.files;
		if (files && files.length > 0) {
			await uploadFile(files[0]);
		}
	}
	
	// Clear image
	function clearImage() {
		formData.image = '';
		imagePreview = null;
		if (fileInput) {
			fileInput.value = '';
		}
	}
	
async function handleSubmit(e) {
	e.preventDefault();
	const testimonialData = {
		id: testimonial?.id || crypto.randomUUID(),
		name: formData.name,
		text: formData.text,
		stars: formData.stars,
		image: formData.image,
		link: formData.link
	};
	onSave(testimonialData);
}
	
	function handleCancel() {
		onCancel();
	}
</script>

{#if isOpen}
	<div class="modal-overlay" onclick={handleCancel} onkeydown={(e) => e.key === 'Escape' && handleCancel()} role="button" tabindex="-1">
		<div class="modal-container" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()} role="dialog" aria-modal="true" tabindex="-1">
			<div class="modal-header">
				<h2 class="modal-title">
					{testimonial ? 'Edit Testamonial' : 'Add New Testamonial'}
				</h2>
				<button class="close-btn" onclick={handleCancel} aria-label="Close modal">
					<i class="fas fa-times"></i>
				</button>
			</div>
			<form onsubmit={handleSubmit} class="modal-form">
				<FormGroup>
					<Label htmlFor="name" required>Name</Label>
					<Input
						type="text"
						name="name"
						bind:value={formData.name}
						placeholder="e.g., Jane Doe"
						required
					/>
				</FormGroup>
				<FormGroup>
					<Label htmlFor="text" required>Testamonial</Label>
					<textarea
						name="text"
						bind:value={formData.text}
						placeholder="What did they say?"
						required
						class="textarea"
						rows="5"
					></textarea>
				</FormGroup>
				<FormGroup>
					<Label htmlFor="stars">Stars (1-5)</Label>
					<Input
						type="number"
						name="stars"
						min="1"
						max="5"
						bind:value={formData.stars}
						placeholder="5"
					/>
				</FormGroup>
				<FormGroup>
					<Label htmlFor="image">Image</Label>
					<div class="image-upload-section">
						{#if imagePreview}
							<div class="image-preview">
								<img src={imagePreview} alt="Testamonial preview" />
								<button 
									type="button" 
									class="clear-image-btn"
									onclick={clearImage}
									disabled={isUploading}
								>
									<i class="fas fa-trash"></i>
									Remove Image
								</button>
							</div>
						{:else}
							<div 
								class="upload-area"
								class:dragging={isDragging}
								ondragover={handleDragOver}
								ondragenter={handleDragEnter}
								ondragleave={handleDragLeave}
								ondrop={handleDrop}
							>
								<input
									bind:this={fileInput}
									type="file"
									name="image"
									accept="image/*"
									onchange={handleFileChange}
									disabled={isUploading}
									class="file-input"
									id="image-upload"
								/>
								<label for="image-upload" class="upload-label">
									<i class="fas fa-cloud-upload-alt"></i>
									<div>
										<p class="upload-text">Click to upload or drag and drop</p>
										<p class="upload-hint">PNG, JPG, GIF up to 5MB</p>
									</div>
								</label>
							</div>
						{/if}
						{#if uploadError}
							<p class="error-message">{uploadError}</p>
						{/if}
						{#if isUploading}
							<p class="uploading-message">Uploading image...</p>
						{/if}
					</div>
				</FormGroup>
				<FormGroup>
					<Label htmlFor="link">Source Link</Label>
					<Input
						type="text"
						name="link"
						bind:value={formData.link}
						placeholder="https://example.com/original-review"
					/>
				</FormGroup>
				<div class="modal-actions">
					<Button type="button" variant="ghost" onclick={handleCancel}>
						Cancel
					</Button>
					<Button type="submit" variant="primary">
						<i class="fas fa-save"></i>
						<span>{testimonial ? 'Update' : 'Create'} Testamonial</span>
					</Button>
				</div>
			</form>
		</div>
	</div>
{/if}

<style lang="scss">
	.modal-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.7);
		backdrop-filter: blur(4px);
		z-index: 2000;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 1rem;
		animation: fadeIn 0.2s ease;
	}
	
	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}
	
	.modal-container {
		background: var(--nav-bg);
		border: 1px solid var(--panel-border);
		border-radius: 16px;
		width: fit-content;
		max-width: 90vw;
		max-height: 90vh;
		overflow-y: auto;
		box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);
		animation: slideUp 0.3s ease;
		
		/* Custom scrollbar */
		&::-webkit-scrollbar {
			width: 8px;
		}
		
		&::-webkit-scrollbar-track {
			background: transparent;
		}
		
		&::-webkit-scrollbar-thumb {
			background: var(--border-primary);
			border-radius: 4px;
		}
		
		&::-webkit-scrollbar-thumb:hover {
			background: var(--accent);
		}
	}
	
	@keyframes slideUp {
		from {
			opacity: 0;
			transform: translateY(20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
	
	.modal-header {
		display: flex;
		// justify-content: space-between;
		align-items:first baseline;
		padding: 1.5rem 2rem;
		border-bottom: 1px solid var(--panel-border);
	}
	
	.modal-title {
		color: var(--text-primary);
		font-size: 1.5rem;
		font-weight: 700;
		margin: 0;
	}
	
	.close-btn {
		width: 36px;
		height: 36px;
		display: flex;
		align-items: center;
		justify-content: center;
		background: transparent;
		border: 1px solid var(--border-secondary);
		border-radius: 8px;
		color: var(--muted);
		cursor: pointer;
		transition: all 0.2s ease;
		position: absolute;
		top: 1.5rem;
		right: 2rem;
		
		&:hover {
			border-color: var(--accent);
			color: var(--accent);
			background: rgba(167, 139, 250, 0.1);
		}
	}
	
	.modal-form {
		padding: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		align-items: center;
		text-align: start;
	}
	
	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
		width: 100%;
		
		@media (max-width: 600px) {
			grid-template-columns: 1fr;
		}
	}
	
	.textarea {
		width: -webkit-fill-available;
		padding: 0.75rem 1rem;
		background: var(--bg-secondary);
		border: 1px solid var(--border-secondary);
		border-radius: 12px;
		color: var(--text-secondary);
		font-size: 1rem;
		outline: none;
		transition: all 0.3s ease;
		font-family: inherit;
		resize: vertical;
		min-height: 120px;
		line-height: 1.5;
		
		&:focus {
			border-color: var(--accent);
			box-shadow: 0 0 0 3px rgba(167, 139, 250, 0.1);
			background: var(--bg-primary);
		}
		
		&::placeholder {
			color: var(--muted-2);
		}
		
		&:hover:not(:focus) {
			border-color: var(--border-primary);
		}
	}
	
	.image-upload-section {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	
	.image-preview {
		position: relative;
		border-radius: 8px;
		overflow: hidden;
		
		img {
			width: 100%;
			height: 300px;
			object-fit: cover;
			display: block;
		}
		
		.clear-image-btn {
			position: absolute;
			top: 0.5rem;
			right: 0.5rem;
			display: flex;
			align-items: center;
			gap: 0.5rem;
			padding: 0.5rem 1rem;
			background: rgba(0, 0, 0, 0.7);
			color: white;
			border: none;
			border-radius: 6px;
			cursor: pointer;
			font-size: 0.9rem;
			transition: all 0.2s ease;
			
			&:hover:not(:disabled) {
				background: rgba(0, 0, 0, 0.9);
				transform: scale(1.05);
			}
			
			&:disabled {
				opacity: 0.5;
				cursor: not-allowed;
			}
		}
	}
	
	.upload-area {
		position: relative;
		display: flex;
		align-items: center;
		justify-content: center;
		
		&.dragging {
			.upload-label {
				border-color: var(--accent);
				background: rgba(167, 139, 250, 0.15);
				transform: scale(1.02);
				
				i {
					color: var(--accent);
					animation: bounce 0.6s ease infinite;
				}
			}
		}
		
		.file-input {
			display: none;
		}
		
		.upload-label {
			width: 100%;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			padding: 2rem;
			border: 2px dashed var(--border-primary);
			border-radius: 8px;
			cursor: pointer;
			transition: all 0.2s ease;
			background: var(--bg-secondary);
			pointer-events: none;
			
			i {
				font-size: 2rem;
				color: var(--accent);
				margin-bottom: 0.5rem;
				transition: all 0.2s ease;
			}
			
			&:hover {
				border-color: var(--accent);
				background: rgba(167, 139, 250, 0.05);
			}
		}
	}
	
	@keyframes bounce {
		0%, 100% {
			transform: translateY(0);
		}
		50% {
			transform: translateY(-10px);
		}
	}
	
	.upload-text {
		color: var(--text-primary);
		font-weight: 600;
		margin: 0;
		font-size: 1rem;
	}
	
	.upload-hint {
		color: var(--muted);
		font-size: 0.85rem;
		margin: 0.25rem 0 0;
	}
	
	.error-message {
		color: #ff6b6b;
		font-size: 0.9rem;
		margin: 0;
	}
	
	.uploading-message {
		color: var(--accent);
		font-size: 0.9rem;
		margin: 0;
		text-align: center;
	}
	
	.field-hint {
		color: var(--muted);
		font-size: 0.85rem;
		margin: 0.5rem 0 0;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		
		i {
			color: var(--accent);
			font-size: 0.8rem;
		}
	}
	
	.modal-actions {
		display: flex;
		justify-content: flex-start;
		gap: 1rem;
		margin-top: 1rem;
		padding-top: 1.5rem;
		border-top: 1px solid var(--panel-border);
		width: 100%;
	}
	
	@media (max-width: 600px) {
		.modal-container {
			max-height: 95vh;
		}
		
		.modal-header,
		.modal-form {
			padding: 1.5rem;
		}
		
		.modal-title {
			font-size: 1.25rem;
		}
	}
</style>
